---
services:
  squid:
    build: .
    container_name: squid
    restart: always
    ports:
      - "3128:3128"   # HTTP
      - "3129:3129"   # HTPPS
    volumes:
      - ./volumes/squid_cache:/var/cache/squid
      - ./volumes/squid_logs:/var/log/squid
      - ./configs/ssl/:/etc/squid/ssl/